<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="User" failures="1" tests="1" name="Validating Text" time="17.448" errors="0" timestamp="20 Apr 2021 08:34:47 GMT">
  <testcase classname="Framework.VerifyTextTest" name="verifyText" time="0.075">
    <failure type="java.lang.AssertionError" message="expected [An Academy to Learn Earn &amp;amp; Shine  in your QA Caree] but found [An Academy to Learn Earn &amp;amp; Shine  in your QA Career]">
      <![CDATA[java.lang.AssertionError: expected [An Academy to Learn Earn & Shine  in your QA Caree] but found [An Academy to Learn Earn & Shine  in your QA Career]
at Framework.VerifyTextTest.verifyText(VerifyTextTest.java:29)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verifyText -->
</testsuite> <!-- Validating Text -->
